# Generated by Django 3.2 on 2021-06-05 07:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import facultyRecruitment.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Jobs',
            fields=[
                ('jobId', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=50)),
                ('position', models.CharField(max_length=40)),
                ('location', models.CharField(default='Udaipur (raj)', max_length=200)),
                ('applyBy', models.DateField(verbose_name='2021-06-05')),
                ('datePosted', models.DateTimeField(default=django.utils.timezone.now)),
                ('description', models.TextField()),
                ('collegeName', models.CharField(max_length=50)),
                ('availablePositions', models.IntegerField()),
                ('image', models.ImageField(upload_to='images/')),
                ('adminPhoneNumber', models.CharField(max_length=10, validators=[facultyRecruitment.validators.validatePhoneNumber])),
                ('adminEmail', models.EmailField(max_length=254)),
                ('collegeWebsite', models.URLField()),
                ('adminId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Applicants',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(default='In-Progress', max_length=50)),
                ('name', models.CharField(max_length=40)),
                ('email', models.EmailField(max_length=40)),
                ('phoneNumber', models.CharField(max_length=13)),
                ('location', models.TextField(max_length=100)),
                ('resume', models.FileField(upload_to='')),
                ('cv', models.FileField(upload_to='')),
                ('linkedInProfileLink', models.URLField()),
                ('portfolioLink', models.URLField()),
                ('queAboutUs', models.TextField()),
                ('jobId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobs.jobs')),
                ('userId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('userId', 'jobId')},
            },
        ),
    ]
