# Generated by Django 3.2 on 2021-06-07 14:19

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CollegeImages',
            fields=[
                ('CollegeId', models.AutoField(primary_key=True, serialize=False)),
                ('collegeName', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='C:\\Users\\am.sa18\\Desktop\\FacultyRecruitment\\facultyRecruitment\\media')),
            ],
        ),
        migrations.RemoveField(
            model_name='jobs',
            name='collegeName',
        ),
        migrations.RemoveField(
            model_name='jobs',
            name='image',
        ),
        migrations.AddField(
            model_name='applicants',
            name='applyDate',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='2021-06-07'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='jobs',
            name='adminPhoneNumber',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='jobs',
            name='applyBy',
            field=models.DateField(verbose_name='2021-06-07'),
        ),
        migrations.AddField(
            model_name='jobs',
            name='collegeId',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='jobs.collegeimages'),
            preserve_default=False,
        ),
    ]
