# Generated by Django 3.2 on 2021-06-07 14:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_remove_jobs_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='applicants',
            name='cv',
        ),
    ]
