# Generated by Django 3.2 on 2021-06-07 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0004_remove_applicants_cv'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicants',
            name='applyDate',
            field=models.DateField(default='2021-06-07'),
        ),
    ]
