# Generated by Django 3.2 on 2021-07-01 10:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('jobs', '0005_alter_applicants_applydate'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='jobs',
            options={'ordering': ['applyBy', '-datePosted']},
        ),
        migrations.AlterField(
            model_name='applicants',
            name='applyDate',
            field=models.DateField(default='2021-07-01'),
        ),
        migrations.AlterField(
            model_name='jobs',
            name='applyBy',
            field=models.DateField(verbose_name='2021-07-01'),
        ),
        migrations.CreateModel(
            name='Reminder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jobId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobs.jobs')),
                ('userId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
