# Generated by Django 3.2 on 2021-07-01 11:22

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('jobs', '0006_auto_20210701_1610'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='reminder',
            unique_together={('userId', 'jobId')},
        ),
    ]
