# Generated by Django 3.2 on 2021-07-03 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0007_alter_reminder_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicants',
            name='applyDate',
            field=models.DateField(default='2021-07-03'),
        ),
        migrations.AlterField(
            model_name='jobs',
            name='applyBy',
            field=models.DateField(verbose_name='2021-07-03'),
        ),
    ]
